### ISSUE TITLE
Precipitation contours

### ISSUE THREAD

**Issue by pdirmeyer** [desmond-gray/Assignment_1#3]
Precipitation is a field where linear color scales do not work well – You can specify specific levels for the contours (see the [matplotlib contourf documentation](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.contourf.html)). For precipitation, powers of two work well (e.g., 0.5, 1, 2, 4, 8, 16, 32 mm/day).

**Comment by desmond-gray** [comment]
I've edited the precipitation contours to a scale that make more sense
